import { db } from "./index";
import { users, suppliers } from "./schema";
import bcrypt from "bcryptjs";

async function seed() {
  console.log("Seeding database...");

  // Create default admin user
  const passwordHash = await bcrypt.hash("admin123", 10);
  await db.insert(users).values([
    {
      name: "Admin User",
      email: "admin@climitra.com",
      passwordHash,
      role: "admin",
      operatingState: "Maharashtra",
    },
    {
      name: "Procurement Manager",
      email: "procurement@climitra.com",
      passwordHash: await bcrypt.hash("procure123", 10),
      role: "procurement_manager",
      operatingState: "Maharashtra",
    },
    {
      name: "Field Agent",
      email: "field@climitra.com",
      passwordHash: await bcrypt.hash("field123", 10),
      role: "field_agent",
      operatingState: "Gujarat",
    },
  ]).onConflictDoNothing();

  // Create test suppliers across states
  await db.insert(suppliers).values([
    {
      businessName: "Rajkot Charcoal Works",
      ownerName: "Ramesh Patel",
      phone: "+91-9876543210",
      email: "ramesh@rajkotcharcoal.com",
      address: "Industrial Area, Rajkot",
      state: "Gujarat",
      district: "Rajkot",
      pinCode: "360001",
      lat: "22.3039",
      lng: "70.8022",
      leadCategories: ["traditional_charcoal"],
      charcoalType: "Hardwood Charcoal",
      species: "Prosopis juliflora",
      form: "lump",
      capacityTonsPerMonth: "50",
      currentAvailability: "30",
      pricePerTon: "18000",
      pricingBasis: "fob",
      fixedCarbonPct: "75",
      moisturePct: "5",
      ashPct: "3",
      volatilePct: "17",
      tier: "preferred",
      source: "manual",
      status: "active",
      internalRating: "4.5",
      certifications: ["ISO 9001"],
    },
    {
      businessName: "Maharashtra Bio Energy",
      ownerName: "Suresh Patil",
      phone: "+91-9876543211",
      email: "suresh@mhbioenergy.com",
      address: "MIDC, Nashik",
      state: "Maharashtra",
      district: "Nashik",
      pinCode: "422001",
      lat: "19.9975",
      lng: "73.7898",
      leadCategories: ["briquette_torrefied"],
      charcoalType: "Bio Briquettes",
      species: "Mixed biomass",
      form: "briquette",
      capacityTonsPerMonth: "100",
      currentAvailability: "60",
      pricePerTon: "12000",
      pricingBasis: "delivered",
      fixedCarbonPct: "68",
      moisturePct: "8",
      ashPct: "5",
      volatilePct: "19",
      tier: "approved",
      source: "manual",
      status: "active",
      internalRating: "3.8",
      certifications: ["Pollution Board Clearance"],
    },
    {
      businessName: "MP Carbon Industries",
      ownerName: "Vikram Singh",
      phone: "+91-9876543212",
      address: "Indore Industrial Area",
      state: "Madhya Pradesh",
      district: "Indore",
      pinCode: "452001",
      lat: "22.7196",
      lng: "75.8577",
      leadCategories: ["traditional_charcoal", "other_charcoal_mfg"],
      charcoalType: "Activated Charcoal",
      species: "Teak wood",
      form: "powder",
      capacityTonsPerMonth: "30",
      currentAvailability: "20",
      pricePerTon: "25000",
      pricingBasis: "fob",
      fixedCarbonPct: "82",
      moisturePct: "3",
      ashPct: "2",
      volatilePct: "13",
      tier: "preferred",
      source: "manual",
      status: "active",
      internalRating: "4.2",
      certifications: ["FSC", "ISO 9001"],
    },
    {
      businessName: "Karnataka Biochar Co-op",
      ownerName: "Manjunath R",
      phone: "+91-9876543213",
      address: "Hubli-Dharwad Road",
      state: "Karnataka",
      district: "Dharwad",
      pinCode: "580001",
      lat: "15.4589",
      lng: "75.0078",
      leadCategories: ["artisanal_biochar"],
      charcoalType: "Biochar",
      species: "Coconut shell",
      form: "lump",
      capacityTonsPerMonth: "15",
      currentAvailability: "10",
      pricePerTon: "22000",
      pricingBasis: "fob",
      fixedCarbonPct: "78",
      moisturePct: "6",
      ashPct: "4",
      volatilePct: "12",
      tier: "approved",
      source: "manual",
      status: "active",
      internalRating: "3.5",
      certifications: [],
    },
    {
      businessName: "Telangana Maize Processing",
      ownerName: "Srinivas Reddy",
      phone: "+91-9876543214",
      address: "Warangal Highway",
      state: "Telangana",
      district: "Warangal",
      pinCode: "506001",
      lat: "17.9784",
      lng: "79.5941",
      leadCategories: ["maize_processing"],
      charcoalType: "Corn Cob Charcoal",
      species: "Maize cob",
      form: "briquette",
      capacityTonsPerMonth: "40",
      currentAvailability: "25",
      pricePerTon: "14000",
      pricingBasis: "delivered",
      fixedCarbonPct: "65",
      moisturePct: "10",
      ashPct: "6",
      volatilePct: "19",
      tier: "probation",
      source: "scraped",
      status: "active",
      internalRating: "2.8",
      certifications: [],
    },
    {
      businessName: "Chhattisgarh Forest Products",
      ownerName: "Rajendra Sahu",
      phone: "+91-9876543215",
      address: "Raipur Industrial Estate",
      state: "Chhattisgarh",
      district: "Raipur",
      pinCode: "492001",
      lat: "21.2514",
      lng: "81.6296",
      leadCategories: ["traditional_charcoal"],
      charcoalType: "Hardwood Charcoal",
      species: "Sal wood",
      form: "lump",
      capacityTonsPerMonth: "70",
      currentAvailability: "45",
      pricePerTon: "16000",
      pricingBasis: "fob",
      fixedCarbonPct: "72",
      moisturePct: "7",
      ashPct: "4",
      volatilePct: "17",
      tier: "approved",
      source: "manual",
      status: "active",
      internalRating: "3.9",
      certifications: ["Pollution Board Clearance"],
    },
    {
      businessName: "Odisha Biomass Energy",
      ownerName: "Prakash Mohanty",
      phone: "+91-9876543216",
      address: "Bhubaneswar Industrial Park",
      state: "Odisha",
      district: "Khurda",
      pinCode: "751001",
      lat: "20.2961",
      lng: "85.8245",
      leadCategories: ["other_charcoal_mfg"],
      charcoalType: "Rice Husk Charcoal",
      species: "Rice husk",
      form: "powder",
      capacityTonsPerMonth: "25",
      currentAvailability: "15",
      pricePerTon: "11000",
      pricingBasis: "fob",
      fixedCarbonPct: "58",
      moisturePct: "12",
      ashPct: "8",
      volatilePct: "22",
      tier: "approved",
      source: "scraped",
      status: "active",
      internalRating: "3.2",
      certifications: [],
    },
    {
      businessName: "Pending Supplier Co",
      ownerName: "Test Pending",
      phone: "+91-9876543217",
      address: "Some Address",
      state: "Tamil Nadu",
      district: "Chennai",
      pinCode: "600001",
      lat: "13.0827",
      lng: "80.2707",
      leadCategories: ["briquette_torrefied"],
      charcoalType: "Torrefied Briquettes",
      form: "briquette",
      capacityTonsPerMonth: "20",
      pricePerTon: "15000",
      tier: "approved",
      source: "self_registered",
      status: "pending_approval",
    },
  ]).onConflictDoNothing();

  console.log("Seed complete!");
  process.exit(0);
}

seed().catch(console.error);
